### PR TITLE
PHP 8.4 Property hooks

### LINKED ISSUE #892: Parser support for PHP 8.4 Asymmetric Property Visibility
- PHP Depend version: 3.x-dev
- PHP Version: 8.4.7
- Installation type: phar file / composer (tried both)
- Operating System / Distribution & Version: MacOS 15.5, Debian 12.11

Prompted by this phpmd issue: https://github.com/phpmd/phpmd/issues/1237

### Current Behavior
When parsing a class utilizing property hooks, I get UnexpectedTokenExceptions.

Examples:
```
class testParserHandlesClassWithPropertyHooks
{
    public private(set) string $data;
}

// exception thrown:

PDepend\Source\Parser\UnexpectedTokenException: Unexpected token: private(set), line: 5, col: 12, file: /Users/mwolff/dev/pdepend/tests/resources/files/Parser/testParserHandlesClassWithPropertyHooks.php.
#0 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8754): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), '/Users/mwolff/d...')
#1 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8741): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1483): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1450): PDepend\Source\Language\PHP\AbstractPHPParser->parseUnknownDeclaration(1000, 1)
#4 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1294): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration(1)
#5 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1102): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#6 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(7141): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#7 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(735): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#8 /Users/mwolff/dev/pdepend/tests/php/PDepend/AbstractTestCase.php(806): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
```

```
class testParserHandlesClassWithPropertyHooks
{
    private string $data;
    public string $foo {
        get {
            return 'foo:' . $this->data;
        }
        set {
            $this->data = $value;
        }
    }
}

// exception thrown:

PDepend\Source\Parser\UnexpectedTokenException: Unexpected token: {, line: 7, col: 24, file: /Users/mwolff/dev/pdepend/tests/resources/files/Parser/testParserHandlesClassWithPropertyHooks.php.
#0 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8754): PDepend\Source\Parser\UnexpectedTokenException->__construct(Object(PDepend\Source\Tokenizer\Token), '/Users/mwolff/d...')
#1 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8741): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException(Object(PDepend\Source\Tokenizer\Token))
#2 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(8710): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedNextTokenException()
#3 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1544): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken(13)
#4 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1475): PDepend\Source\Language\PHP\AbstractPHPParser->parseFieldDeclaration()
#5 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1450): PDepend\Source\Language\PHP\AbstractPHPParser->parseUnknownDeclaration(11, 1)
#6 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1294): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration(1)
#7 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(1102): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#8 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(7141): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#9 /Users/mwolff/dev/pdepend/src/Source/Language/PHP/AbstractPHPParser.php(735): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#10 /Users/mwolff/dev/pdepend/tests/php/PDepend/AbstractTestCase.php(806): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
```

### Expected Behavior
The parser does not throw an exception when encountering property hooks or short property declarations
with asymmetric visibility.

### Steps To Reproduce:
I prepared a PR with a new testcase ParserTest::testParserHandlesClassWithPropertyHooks(), along with an example class file. The test shows the above behaviour on invokation.

PR here: https://github.com/pdepend/pdepend/pull/893

(Side note: To make the test suite run without other failures, I also had to bump PHPUnit to ^11.0 and Paratest to ^7.6. After doing so, composer install works on PHP 8.4 and the test suite runs fine when excluding the new testcase, but show quite a lot of deprecations.)

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

### LINKED ISSUE #898: Parser support for PHP 8.4 property hooks
This feature would:

- Add parser support for **PHP 8.4 property hooks**, i.e., the `get` and `set` blocks in property declarations:

```php
    class Example {
        public string $foo {
            get {
                return 'value';
            }
            set {
                $this->foo = $value;
            }
        }
    }
```

- Parse the `get` and `set` blocks correctly without throwing an `UnexpectedTokenException`.  
- Build the corresponding AST nodes for the property body, associating the getter and setter with the property.  

**Benefits:**

- Enables PDepend to understand PHP 8.4 property hooks.  
- Allows accurate static analysis of properties with custom getters and setters.  

**Consequences:**

- May involve adding new AST node types or metadata to represent property hooks.  

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Support nullable types".

### PR DESCRIPTION
**Pull request by AJenbo**
Type: feature
Issue: #898
Breaking change: no

fixes #892
fixes #898

This PR add support for PHP 8.4 [property hooks](https://www.php.net/manual/en/language.oop5.property-hooks.php).

It also improves a few corner cases for Asymmetric Property Visibility.

### CODE REVIEW

File: src/Source/Language/PHP/AbstractPHPParser.php [hunk 1]
```diff
@@ -7966,9 +8007,7 @@ private function parseStaticValue(): ?ASTValue
 
         while ($tokenType !== Tokenizer::T_EOF) {
             switch ($tokenType) {
-                case Tokens::T_COMMA:
-                case Tokens::T_SEMICOLON:
-                case Tokens::T_PARENTHESIS_CLOSE:
+                case $this->isStaticValueTerminator():
```
Comment (kylekatarnls) [inline src/Source/Language/PHP/AbstractPHPParser.php]: `$tokenType` checked against `bool` can lead to unexpected weak-comparison and is confusing. (Also it implies that we re-call `$this->tokenizer->peek()`)

File: src/Source/Language/PHP/PHPTokenizerInternal.php [hunk 2]
```diff
@@ -910,17 +907,15 @@ private function substituteTokens(array $tokens): array
...
+            ) {
                 $asymmetricToken = true;
                 $result[] = match ($temp) {
                     T_PRIVATE => [T_PRIVATE_SET, 'private(set)', $token[2]],
                     T_PROTECTED => [T_PROTECTED_SET, 'protected(set)', $token[2]],
                     T_PUBLIC => [T_PUBLIC_SET, 'public(set)', $token[2]],
                 };
-
-                continue;
             } else {
```
Comment (kylekatarnls) [inline src/Source/Language/PHP/PHPTokenizerInternal.php]: Not related to this PR, but this method really has an insane number of complexity paths and nesting.

Also `else` is discouraged by PHPMD so at some point we should go for separated `if (condition) { stuff(); continue;}, then with:

```php
if (foo) {
  foo();

  continue;
}

if (bar) {
  bar();

  continue;
}

something_else();
```

rather than:
```php
if (foo) {
  foo();
} elseif (bar) {
  bar();
} else {
  something_else();
}
```
it's no longer glued and we could add/remove/re-order if-blocks without changing keywords used and with a cleaner git-diff.

Comment (AJenbo) [reply src/Source/Language/PHP/PHPTokenizerInternal.php]: I saw that it had turned in to a mix of styles and went with the original one.

File: src/Source/Language/PHP/AbstractPHPParser.php (hunk 1 above)
Comment (AJenbo) [reply src/Source/Language/PHP/AbstractPHPParser.php]: I mirrored the solution used a bit further down in the same switch:

https://github.com/pdepend/pdepend/blame/ddcb6ce58a9a7f6e6491ed4cf4819c5ed95bc81f/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php#L2557

I do agree with all your points though :)

Do you have a suggestion for how I could do it instead?

File: src/Source/Language/PHP/PHPTokenizerInternal.php (hunk 2 above)
Comment (AJenbo) [reply src/Source/Language/PHP/PHPTokenizerInternal.php]: Fixed

File: src/Source/Language/PHP/AbstractPHPParser.php (hunk 1 above)
Comment (AJenbo) [reply src/Source/Language/PHP/AbstractPHPParser.php]: I remove the redundant calls to `$this->tokenizer->peek()` (also for the existing cases)

Comment (AJenbo) [reply src/Source/Language/PHP/AbstractPHPParser.php]: Alright I think I have managed to rewrite all the offending cases to not abuse switches.

**Review by kylekatarnls — APPROVED** [review]
