### PR TITLE
Re-allow empty compilation unit

### LINKED ISSUE #682: Critical Error: A compilation unit should contain at least one token
- PHP Depend version: 2.15.0
- PHP Version: 7.4.33
- Installation type: composer
- Operating System / Distribution & Version: GNU/Linux Ubuntu 5.15.0-83-generic x86_64

### Current Behavior
Critical error while "parsing source files": 
```
Critical error:
===============
A compilation unit should contain at least one token
```
### Expected Behavior
No errors while parsing source files (version 2.14.0).

### Steps To Reproduce:

```sh
vendor/bin/pdepend --summary-xml=./summary.xml src
```

## Checks before submitting
* [✓ ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [✓ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [✓ ] I have added every step to reproduce the bug.
* [✓ ] If possible I added relevant code examples.
* [✓ ] This issue is about 1 bug and nothing more.
* [ ✓] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #682
Breaking change: it actually revert an unwanted breaking change from 2.15.0

### CODE REVIEW

File: src/main/php/PDepend/Source/Parser/TokenStack.php [hunk 1]
```diff
@@ -99,7 +99,7 @@ public function push()
     public function pop()
     {
         $tokens       = $this->tokens;
-        $this->tokens = $this->stack[--$this->offset];
+        $this->tokens = isset($this->stack[--$this->offset]) ? $this->stack[$this->offset] : array();
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/Parser/TokenStack.php:102]: This is to strictly guarantee that PHPDoc types are respected: `$this->tokens` is always an `array`, and `pop()` always returns an `array`

**Review by AJenbo — APPROVED** [review]
