### PR TITLE
(fix): match expression does not have namespace

### LINKED ISSUE #531: "Unexpected token: =>," when referencing an external constant on left part of match expression
- PHP Depend version: 2.9.1
- PHP Version: 8.0
- Installation type: (composer)
- Operating System / Distribution & Version: Ubuntu

### Current Behavior
`ERROR while parsing` on the line where a constant is referenced

### Expected Behavior
No parsing error.

### Steps To Reproduce:
Given this file:
```php
<?php
namespace Home;

class A {
    private function getText(string $type): string
    {
        return match ($type) {
            B::C => 'hello'
        };
    }
}
```

When I run `phpmd test.php ansi cleancode`, The following error appears:
```
#0 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7322): PDepend\Source\Parser\UnexpectedTokenException->__construct()
#1 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(7288): PDepend\Source\Language\PHP\AbstractPHPParser->getUnexpectedTokenException()
#2 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2014): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken()
#3 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2076): PDepend\Source\Language\PHP\AbstractPHPParser->parseIndexExpression()
#4 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1982): PDepend\Source\Language\PHP\AbstractPHPParser->parseStringIndexExpression()
#5 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4088): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalIndexExpression()
#6 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion80.php(224): PDepend\Source\Language\PHP\AbstractPHPParser->parseFunctionPostfix()
#7 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4030): PDepend\Source\Language\PHP\PHPParserVersion80->parseFunctionPostfix()
#8 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4493): PDepend\Source\Language\PHP\AbstractPHPParser->parseMemberPrefixOrFunctionPostfix()
#9 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2772): PDepend\Source\Language\PHP\AbstractPHPParser->parseVariableOrConstantOrPrimaryPrefix()
#10 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3831): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#11 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(3849): PDepend\Source\Language\PHP\AbstractPHPParser->buildReturnStatement()
#12 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6007): PDepend\Source\Language\PHP\AbstractPHPParser->parseReturnStatement()
#13 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5944): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#14 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1278): PDepend\Source\Language\PHP\AbstractPHPParser->parseScope()
#15 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1231): PDepend\Source\Language\PHP\AbstractPHPParser->parseCallableDeclaration()
#16 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(988): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodDeclaration()
#17 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion74.php(87): PDepend\Source\Language\PHP\AbstractPHPParser->parseMethodOrFieldDeclaration()
#18 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(887): PDepend\Source\Language\PHP\PHPParserVersion74->parseMethodOrFieldDeclaration()
#19 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(723): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody()
#20 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6075): PDepend\Source\Language\PHP\AbstractPHPParser->parseClassDeclaration()
#21 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(397): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#22 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(587): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#23 /srv/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(335): PDepend\Engine->performParseProcess()
#24 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(95): PDepend\Engine->analyze()
#25 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(192): PHPMD\Parser->parse()
#26 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(103): PHPMD\PHPMD->processFiles()
#27 /srv/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(148): PHPMD\TextUI\Command->run()
#28 /srv/vendor/phpmd/phpmd/src/bin/phpmd(61): PHPMD\TextUI\Command::main()
#29 {main}

Found 0 violations and 1 error in 17ms
```

Interestingly, the error doesn't show if I don't specify a namespace at the beginning of the file.

## Checks before submitting
* [ x ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [ x ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [ x ] I have added every step to reproduce the bug.
* [ x ] If possible I added relevant code examples.
* [ x ] This issue is about 1 bug and nothing more.
* [ x ] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

### PR DESCRIPTION
**Pull request by lucassabreu**
Type: bugfix
Issue: fix #531
Breaking change: no

The keyword `match` is being treated as if it could have a namespace,
but in PHP 8 you can't use `match` in your code, given it is a reserved
word now.

This fix does keep match as a Tokens::T_STRING, but if the maintainers
prefer that I change it to use a new token id (Tokens::T_MATCH), I can
invest more time to change and fix that way.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
I think the approach is correct. ideal solution would make `getImage()` returning with namespace for PHP < 8 and without for >= 8 but it would need to make the node aware of the version or as you propose to have dynamic token (match for >= 8, string for < 8), this can be a bit painful and risky, it will be easier to fix in our next major version when we'll drop old PHP versions.

This PR is a proper way to fix the namespace support for match without breaking the PHP 7 behavior.

File: src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php [hunk 1]
```diff
@@ -58,14 +58,33 @@ class MatchExpressionTest extends PHPParserVersion80Test
...
+    {
+        $this->checkMatchExpression('Baz');
+    }
+
+    /**
+     * @return void
+     */
+    private function checkMatchExpression(string $namespacePrefix = null)
+    {
+        $matchImage = implode('\\', array_filter([$namespacePrefix, 'match']));
```
Comment (kylekatarnls) [inline src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php:77]: Fix PHP 5.3 compatibility
```suggestion
        $matchImage = implode('\\', array_filter(array($namespacePrefix, 'match')));
```

**Review by kylekatarnls — APPROVED** [review]

File: src/main/php/PDepend/Source/AST/AbstractASTNode.php [hunk 2]
```diff
@@ -43,6 +43,8 @@
 
 namespace PDepend\Source\AST;
 
+use function array_pop;
+
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/AST/AbstractASTNode.php:47]:
```suggestion
```

**Review by kylekatarnls — DISMISSED** [review]

File: src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php [hunk 3]
```diff
@@ -58,14 +58,33 @@ class MatchExpressionTest extends PHPParserVersion80Test
...
+     */
+    public function testMatchExpressionWithNamespace()
+    {
+        $this->checkMatchExpression('Baz');
+    }
+
+    /**
+     * @return void
+     */
+    private function checkMatchExpression(string $namespacePrefix = null)
```
Comment (kylekatarnls) [inline src/test/php/PDepend/Source/Language/PHP/Features/PHP80/MatchExpressionTest.php:75]:
```suggestion
    private function checkMatchExpression($namespacePrefix = null)
```

**Review by kylekatarnls — APPROVED** [review]

**Comment by lucassabreu** [comment]
hi @kylekatarnls, thank you for fixing my mistakes hehe

by what i did understand the fix is right, right?

the part about removing the namespace diretatly on the `getImage` on this comment made me a little confused if it was enought.
https://github.com/pdepend/pdepend/pull/537#issuecomment-843885831

**Comment by kylekatarnls** [comment]
Yes, this PR is good to be merged to me, I let a chance for the rest of the team to make comment then I'll merge it. The rest of the mentioned possible improvement would be better handled in the next major version (but our branch for it is not ready to receive PRs).
