### PR TITLE
Fix #299 Class constant expression declaration

### LINKED ISSUE #299: ASTConstantDeclarator crash on array concat with named keys
This will crash pdepend

```
class Test
{
    const A = [];
    const B = self::A + ['a' => 1];
}
```

Log:
`PDepend @package_version@

Parsing source files:
.......
Creating: \PDepend\Source\AST\ASTNamespace(Kontent_Auth\Adapter)......................
Creating: \PDepend\Source\AST\ASTNamespace(Site_Controller\Kontent_Controller).......
Creating: \PDepend\Source\AST\ASTNamespace(Kontent_Field)....
Processing file /home/ajenbo/code/test.php
Creating: \PDepend\Source\AST\ASTConstantDefinition(const)
Creating: \PDepend\Source\AST\ASTConstantDeclarator(A)
Creating: \PDepend\Source\AST\ASTArray()
Creating: \PDepend\Source\AST\ASTConstantDefinition(const)
Creating: \PDepend\Source\AST\ASTConstantDeclarator(B)PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\ASTConstantDeclarator::setValue() must be an instance of PDepend\Source\AST\ASTValue, null given, called in /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6118 and defined in /usr/share/php/PDepend/Source/AST/ASTConstantDeclarator.php:107
Stack trace:
#0 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6118): PDepend\Source\AST\ASTConstantDeclarator->setValue(NULL)
#1 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6053): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDeclarator()
#2 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(839): PDepend\Source\Language\PHP\AbstractPHPParser->parseConstantDefinition()
#3 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(666): PDepend\Source\Language\PHP\AbstractPHPParser->parseTypeBody(Object(PDepend\Source\AST\ASTClass))
#4 /usr/share/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5669): PDepend\Sour in /usr/share/php/PDepend/Source/AST/ASTConstantDeclarator.php on line 107`

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #299
Breaking change: no

### CODE REVIEW

File: src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php [hunk 1]
```diff
@@ -165,16 +165,4 @@ protected function parseStaticValueVersionSpecific(ASTValue $value)
 
         return $value;
     }*/
-
-    /**
-     * Parses constant default values as they are supported by the most recent
-     * PHP version.
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/Language/PHP/PHPParserGeneric.php:171]: But this has been written before PHP 7.0 was released, that's why this override was obsolete and should be removed.

File: src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testConstantArrayConcatenation.php [hunk 2]
```diff
@@ -0,0 +1,7 @@
+<?php
+
+class Test
+{
+    const A = [];
+    const B = self::A + ['a' => 1];
+}
```
Comment (kylekatarnls) [inline src/test/resources/files/Source/Language/PHP/PHPParserVersion74/testConstantArrayConcatenation.php:7]: Test with PHP 7.4

File: src/test/resources/files/bugs/299/testConstantArrayConcatenation.php [hunk 3]
```diff
@@ -0,0 +1,7 @@
+<?php
+
+class Test
+{
+    const A = [];
+    const B = self::A + ['a' => 1];
+}
```
Comment (kylekatarnls) [inline src/test/resources/files/bugs/299/testConstantArrayConcatenation.php:7]: Test with top-extended PHPParser (future stable releases we'll implement as a parser)

File: src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php [hunk 4]
```diff
@@ -291,4 +296,62 @@ public function testNumericLiteralSeparator()
...
+    /**
+     * @param \PDepend\Source\Tokenizer\Tokenizer $tokenizer
+     * @param \PDepend\Source\Builder\Builder $builder
+     * @param \PDepend\Util\Cache\CacheDriver $cache
+     * @return \PDepend\Source\Language\PHP\AbstractPHPParser
+     */
+    protected function createPHPParser(Tokenizer $tokenizer, Builder $builder, CacheDriver $cache)
+    {
+        return $this->getAbstractClassMock(
+            'PDepend\\Source\\Language\\PHP\\PHPParserVersion74',
```
Comment (kylekatarnls) [inline src/test/php/PDepend/Source/Language/PHP/PHPParserVersion74Test.php:353]: Use PHPParserVersion74 instead of PHPParserGeneric

File: src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php [hunk 5]
```diff
@@ -194,4 +197,18 @@ public function testTrailingCommasInCall()
...
+    /**
+     * @param \PDepend\Source\Tokenizer\Tokenizer $tokenizer
+     * @param \PDepend\Source\Builder\Builder $builder
+     * @param \PDepend\Util\Cache\CacheDriver $cache
+     * @return \PDepend\Source\Language\PHP\AbstractPHPParser
+     */
+    protected function createPHPParser(Tokenizer $tokenizer, Builder $builder, CacheDriver $cache)
+    {
+        return $this->getAbstractClassMock(
+            'PDepend\\Source\\Language\\PHP\\PHPParserVersion73',
```
Comment (kylekatarnls) [inline src/test/php/PDepend/Source/Language/PHP/PHPParserVersion73Test.php:210]: Use PHPParserVersion73 instead of PHPParserGeneric for PHP 7.3 tests

File: src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php [hunk 6]
```diff
@@ -99,4 +102,18 @@ public function testAbstractMethodOverriding()
...
+    /**
+     * @param \PDepend\Source\Tokenizer\Tokenizer $tokenizer
+     * @param \PDepend\Source\Builder\Builder $builder
+     * @param \PDepend\Util\Cache\CacheDriver $cache
+     * @return \PDepend\Source\Language\PHP\AbstractPHPParser
+     */
+    protected function createPHPParser(Tokenizer $tokenizer, Builder $builder, CacheDriver $cache)
+    {
+        return $this->getAbstractClassMock(
+            'PDepend\\Source\\Language\\PHP\\PHPParserVersion72',
```
Comment (kylekatarnls) [inline src/test/php/PDepend/Source/Language/PHP/PHPParserVersion72Test.php:115]: Use PHPParserVersion72 instead of PHPParserGeneric for PHP 7.2 tests

File: src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php [hunk 7]
```diff
@@ -100,4 +99,9 @@ protected function parseArray(ASTArray $array, $static = false)
 
         return $array;
     }
+
+    protected function parseConstantDeclaratorValue()
+    {
+        return $this->parseStaticValue();
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php:105]: Before PHP 5.6: constant declaration should be fully scalar and static (no expression, no array).

File: src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+/**
+ * Base interface for php code tokenizers that can access any token anytime.
+ *
+ * - Are able to return previously emitted token.
+ * - Are able to return token from the not yet buffered string.
+ *
+ * @copyright 2008-2017 Manuel Pichler. All rights reserved.
+ * @license http://www.opensource.org/licenses/bsd-license.php BSD License
+ */
+interface FullTokenizer
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php:52]: New interface introduced for 2 reasons:

1. Avoid breaking change by changing the existing `Tokenizer` interface.

2. Our PHPTokenizerInternal is actually able to access any token as it tokenize the whole string (file) at once. While reading progressively the file would be way more optimized, it's also way more difficult to achieve and it's just not what our tokenizer actually do. So the `Tokenizer` interface can continue to represent the minimum that an hypothetical optimized tokenizer must support. And `FullTokenizer` would be what we actually can do with no limitation. But keeping fallbacks when `!($this->tokenizer instanceof FullTokenizer)` would allow us to create some day a more optimized tokenizer (which could only support `Tokenizer` but would not have to support `FullTokenizer`).

Comment (tvbeek) [reply src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php:52]: Thanks for the explanation, the only question I have: isn't it in fact an extension of the Tokenizer interface and should it extend the Tokenizer interface?

Comment (kylekatarnls) [reply src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php:52]: Indeed, else I should rename it.

Comment (kylekatarnls) [reply src/main/php/PDepend/Source/Tokenizer/FullTokenizer.php]: Fixed.

File: src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php [hunk 9]
```diff
@@ -56,7 +56,6 @@
  */
 abstract class PHPParserVersion53 extends AbstractPHPParser
 {
-
```
[the remark this answers is not in the document]
Comment (kylekatarnls) [reply src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php]: Fixed.

File: src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php [hunk 10]
```diff
@@ -7133,6 +7133,7 @@ protected function consumeToken($tokenType)
     protected function consumeComments()
     {
         $type = $this->tokenizer->peek();
+
```
[the remark this answers is not in the document]
Comment (kylekatarnls) [reply src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php]: Fixed.
