### PR TITLE
Fix #473 handle skipped variable in destructuring array

### LINKED ISSUE #473: Missing variables on shorthand list syntax throws an Exception
- PHP Depend version: 2.7.1
- PHP Version:7.4.4
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 19.04

### Current Behaviour
When you omit the first option of a list (using the shorthand syntax) it throws an Exception

For example:

```
[, $testA, $testB, $testC] = [1,2,3,4];
```
throws
```
The parser has reached an invalid state near line "171" in file "file_path". Please check the following conditions: Mandatory expression expected.
```

### Expected Behaviour
The expected behaviour would be that it parses it correctly like a `list` - Note: if you change the shorthand syntax to be `list` then it works. 

### Steps To Reproduce:
```
[, $testA, $testB, $testC] = [1,2,3,4];
```

Should trigger the error message - This was found as part of PHPMD: See https://github.com/phpmd/phpmd/issues/727

### Further Info

It looks like the issue is down to the switch case in `src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php` Line 2738. The If statement will return true for shorthand syntax lists and will deal with them as an array instead of list (See line 2767 for the list & shorthand list syntax case) but this is never hit in this case. 

Happy to take a look into this issue

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #473
Breaking change: no

### CODE REVIEW

File: src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php [hunk 1]
```diff
@@ -224,4 +224,9 @@ protected function parseCatchExceptionClass(ASTCatchStatement $stmt)
             }
         } while ($repeat === true);
     }
+
+    protected function canHaveCommaBetweenArrayElements()
```
Comment (ravage84) [inline src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php:228]: This method should inherit the doc block of the super class.

Comment (kylekatarnls) [reply src/main/php/PDepend/Source/Language/PHP/PHPParserVersion71.php:228]: #477
