### PR TITLE
Make sockets optional, fix serialization on docker

### LINKED ISSUE #913: Uncaught AssertionError
- PHP Depend version: 3.x
- PHP Version: 8.4
- Installation type: composer
- Operating System / Distribution & Version: (Windows 10 / CentOS 7.6 / ...)

### Current Behavior
```
Fatal error: Uncaught AssertionError: assert(is_callable($process->stdout)) in /var/www/vendor/pdepend/pdepend/src/Engine.php:589
Stack trace:
#0 /var/www/vendor/pdepend/pdepend/src/Engine.php(589): assert(false, 'assert(is_calla...')
#1 /var/www/vendor/pdepend/pdepend/src/Engine.php(530): PDepend\Engine->runMultiProcessParse(Object(ArrayIterator), 528, 8)
#2 /var/www/vendor/pdepend/pdepend/src/Engine.php(299): PDepend\Engine->performParseProcess()
#3 /var/www/vendor/phpmd/phpmd/src/Parser.php(97): PDepend\Engine->analyze()
#4 /var/www/vendor/phpmd/phpmd/src/PHPMD.php(221): PHPMD\Parser->parse(Object(PHPMD\Report))
#5 /var/www/vendor/phpmd/phpmd/src/TextUI/Command.php(158): PHPMD\PHPMD->processFiles('src/', Array, Array, Array, Object(PHPMD\Report))
#6 /var/www/vendor/phpmd/phpmd/src/TextUI/Command.php(227): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))
#7 /var/www/vendor/phpmd/phpmd/bin/phpmd(49): PHPMD\TextUI\Command::main(Array)
#8 /var/www/vendor/bin/phpmd(119): include('/var/www/vendor...')
#9 {main}
  thrown in /var/www/vendor/pdepend/pdepend/src/Engine.php on line 589
```

Error happened after recent changes

### PR DESCRIPTION
**Pull request by AJenbo**
Type: bugfix
Fixes #913
Breaking change: no

- Fixes serialization of `ASTMethod` and `ASTTrait` in docker (I don't know specifically why it's more picky then a regular installation on Debian/Ubuntu)
- Make ext-sockets optional (but suggested for Windows
- Fix deprecation as suggested here https://github.com/pdepend/pdepend/commit/a348a12d483e221f8e0e027953f3b5437d700f41#r173362126
- Added a test for anonymous classes with properties

I have tested by running it on the pdepend root (including all tests, fixtures, and vendor folders) and the vender folder of a large package (18k files) which uncovered one more issue (`ASTMethod`) then what was reported in #913.

### CODE REVIEW

File: src/Source/AST/ASTClass.php [hunk 1]
```diff
@@ -63,7 +63,13 @@ class ASTClass extends AbstractASTClassOrInterface
 
     public function __sleep(): array
     {
-        return ['properties', ...parent::__sleep()];
+        $properties = parent::__sleep();
+
+        if (static::class === self::class) {
+            return ['properties', ...$properties];
```
Comment (kylekatarnls) [inline src/Source/AST/ASTClass.php:69]: This change is related to the serialization failure on docker?

**Review by kylekatarnls — APPROVED** [review]

File: src/Source/AST/ASTClass.php (hunk 1 above)
Comment (AJenbo) [reply src/Source/AST/ASTClass.php:69]: Yes, `$properties` is private to `ASTClass`, which triggers a serialization warning. My other consideration was to turn it into a protected property but that causes some tests to fail.
