### PR TITLE
Fix #472 Use the current token instead of the first inner one to determine the class start

### LINKED ISSUE #472: Incorrect detection start line for Class
- PHP Depend version: 2.7.1
- PHP Version: 7.3.10
- Installation type: composer
- Operating Ubuntu 16

Related issue
https://github.com/phpmd/phpmd/issues/739

pdepend give incorrect start line for class when there is a constanct with access modifier in class.

### PR DESCRIPTION
**Pull request by kylekatarnls**
Type: bugfix
Issue: Fix #472 Fix phpmd/phpmd#739 ([confirmed](https://github.com/phpmd/phpmd/issues/739#issuecomment-631893513))
Breaking change: no

### CODE REVIEW

**Comment by sveneld** [comment]
Please add this fix to milestone 2.7.2

**Comment by kylekatarnls** [comment]
It will be in the next version very likely, but the milestone 2.7.2 will probably be transformed into a 2.8.0 release since we added 2 features:
- Added #458: Support trait insteadof overrides
- Added #466: Allow to configure file cache ttl in configuration file.

File: src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php [hunk 1]
```diff
@@ -5883,8 +5884,6 @@ private function parseOptionalStatement()
             case Tokens::T_ENDFOREACH:
             case Tokens::T_CURLY_BRACE_CLOSE:
                 return null;
-            case Tokens::T_DECLARE:
-                return $this->parseDeclareStatement();
```
Comment (kylekatarnls) [inline src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php:5887]: This is an exact duplicate of just above in the same switch: https://github.com/pdepend/pdepend/pull/478/files#diff-1cdb010483dd4c3d254da8d8f8462aa8R5875
